apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderitemwebapplication-deployment
  labels:
    app: orderitemwebapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderitemwebapplication
  template:
    metadata:
      labels:
        app: orderitemwebapplication
    spec:
      containers:
      - name: orderitemwebapplication
        image: orderitemcontainer.azurecr.io/orderitemserviceimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisecretkey
---
apiVersion: v1
kind: Service
metadata:
  name: orderitemwebappplicationsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: orderitemwebapplication